Exp - 5 Code review
virtual-labs/exp-chain-of-inverters-iiith pull request #6
Opened 2022-04-13 17:06 UTC by srisatyavinay

2022-04-15 08:32 UTC, vjspranav reviewed
looks good to me, in integer.js (in all experiments)
It feels like a lot of code is being re written. Multiple functions have almost the same set of lines.

2022-04-15 12:12 UTC, srisatyavinay commented
As of now the images are not correct. We will change the image src soon.

2022-04-19 06:58 UTC, raj-vlabs requested changes
Please look at the comments on exp-1. Most of the problems are common. Please resolve those comments for this exp too:
1. Please use strict mode
2. Please use descriptive variable names.
3. Please import only 1 main.js as a module in the html file. Import everything else inside main.js. Keep all the initial logic inside main.js instead of littering it on the html file

2022-04-19 06:58 UTC, raj-vlabs commented on experiment/simulation/css/main.css
> +    min-height: 2.96875rem;
Please reduce the precision

2022-04-19 06:58 UTC, raj-vlabs commented on experiment/simulation/index.html
> +					Required no.of components of this type are already present in the workspace
Please add space between no. and of

2022-04-19 06:58 UTC, raj-vlabs commented on experiment/simulation/index.html
> +	<script src="js/inverter.js"></script>
Please create a main.js file and import it as a module in the html file. Then import all the other files into main.js.

2022-04-19 06:58 UTC, raj-vlabs commented on experiment/simulation/js/components.js
> +const jsplumbInstance = jsPlumb.getInstance({
Please use strict mode

2022-04-19 06:58 UTC, raj-vlabs commented on experiment/simulation/js/components.js
> +        const r = s.concat("$", t);
You can use a template literal here:
const connectionId = `${connectionSrc}\$${connectionTarget}`

2022-04-19 06:58 UTC, raj-vlabs commented on experiment/simulation/js/components.js
> +    for (i = 0; i < con.length; i++) {
Please refactor using con.forEach here.

jsplumbInstance.getAllConnections().forEach(connection => {
const connectionId = \`${connection.sourceId}\$${connection.targetId}\`
connectionMap.set(connectionId, connection.targetId)
});

2022-04-19 23:02 UTC, srisatyavinay commented on experiment/simulation/js/components.js
> +    for (i = 0; i < con.length; i++) {
Did that.

2022-04-19 23:02 UTC, srisatyavinay commented on experiment/simulation/js/components.js
> +        const r = s.concat("$", t);
Used it.

2022-04-19 23:02 UTC, srisatyavinay commented on experiment/simulation/js/components.js
> +const jsplumbInstance = jsPlumb.getInstance({
Used strict mode

2022-04-19 23:02 UTC, srisatyavinay commented on experiment/simulation/css/main.css
> +    min-height: 2.96875rem;
Reduced it.

2022-04-19 23:03 UTC, srisatyavinay commented on experiment/simulation/index.html
> +					Required no.of components of this type are already present in the workspace
Added it.

2022-04-19 23:03 UTC, srisatyavinay commented on experiment/simulation/index.html
> +	<script src="js/inverter.js"></script>
As told in exp-1 it will take a lot of time to do that. So we request you to allow us leave this part

2022-07-21 15:54 UTC, raj-vlabs requested changes
1. The demo of this experiment is not correct. The delay in the propagation of the signal should come between the signal entering an inverter and exiting one. Currently the signals are moving at different speeds on open wire.
2. The instructions on the Practice are not clear. It doesn't say anywhere that 5 inverters have to be put on the circuit.
3. Please use https links strictly.

2022-07-21 18:05 UTC, Aditya-debug15 commented on experiment/simulation/js/animation.js
> +const svgns = "http://www.w3.org/2000/svg";
Tried changing that to https gsap was giving some errors. All the links in HTML file are changed to https

2022-07-21 18:09 UTC, Aditya-debug15 commented on experiment/simulation/js/animation.js
> +        else if (timeline.progress() === 1) {
this condition was handled in stopCircuit function so removed this block

2022-07-21 18:09 UTC, Aditya-debug15 commented on experiment/simulation/js/animation.js
> +        observ.innerHTML = "Simulation has been stopped.";
Replaced

2022-07-21 18:10 UTC, Aditya-debug15 commented on experiment/simulation/index.html
> +							<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
Removed

2022-07-21 18:10 UTC, Aditya-debug15 commented on experiment/simulation/demo.html
> +                        <path id="path1NOT" class="gate-demo" d="M 750 630 L 750 600 L 790 630 L 750 660 L 750 630 " />
It was not needed so removed it

2022-07-21 18:12 UTC, Aditya-debug15 commented on experiment/pretest.json
> +    "correctAnswer": "b["
Fixed it. We had not written this file so we didn't look into it in great detail earlier assuming that it would be correct. We have corrected it now

2022-07-21 18:13 UTC, Aditya-debug15 commented on experiment/pretest.json
> +    "question": "2. What you mean by delay?",
changed it

2022-07-21 18:13 UTC, Aditya-debug15 commented on experiment/pretest.json
> +      "a": "Increases by n2",
NOw using superscripts. We had not written this file so we didn't look into it in great detail earlier assuming that it would be correct. We have corrected it now

2022-07-21 18:16 UTC, Aditya-debug15 commented on experiment/pretest.json
> +    "question": "8. For minimm delay, what is the no of inverters in the chain connected in series?",
Fixed the spelling. We had not written this file so we didn't look into it in great detail earlier assuming that it would be correct. We have corrected it now

2022-07-22 09:30 UTC, raj-vlabs approved these changes

2022-07-22 09:30 UTC, merged